services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: daily_diet
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tiagoltavares2002@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Senha123
      PGADMIN_LISTEN_PORT: 8080
    ports:
    - 8080:8080

volumes:
  db_data:
    driver: local